version: "3.8"


services:
  web:
    build:
      context: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8050:8000
    env_file: .env
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    env_file: .env